<?php
/**
 * @file
 * Module file for qtrClientWS.
 */

/**
 * Implements hook_default_wsclient_service().
 *
 * Defines web service descriptions (one public and one private).
 * This hook is invoked when web service descriptions
 * are loaded like this:
 *     $qtr = wsclient_service_load('dev.l10n.org.xx');
 *     $result = $qtr->statistics('sq');
 */
function qtrClientWS_default_wsclient_service() {
  module_load_include('inc', 'qtrClientWS', 'public');
  module_load_include('inc', 'qtrClientWS', 'authenticated');

  $services['public_qtr'] = _qtrClientWS_public('public_qtr');
  $services['qtr'] = _qtrClientWS_authenticated('qtr');
  return $services;
}
