<?php
/**
 * @file
 * Module file for qtrProject.
 */

module_load_include('inc', 'qtrProject', 'blocks/blocks');

/**
 * Implements hook_init().
 */
function qtrProject_init() {
  // Include the stylesheets.
  $path = drupal_get_path('module', 'qtrProject');
  drupal_add_css($path . '/blocks/list.css.less');
  drupal_add_css($path . '/blocks/select.css.less');
  drupal_add_css($path . '/blocks/subscribe.css.less');
}

/**
 * Implements hook_menu().
 */
function qtrProject_menu() {
  $items['qtr/project'] = array(
    'type'            => MENU_NORMAL_ITEM,
    'title'           => 'Project List',
    'description'     => 'List of all the imported projects.',
    'page callback'   => 'qtrProject_projlist',
    'file'            => 'callback/projlist.inc',
    'access callback' => TRUE,
  );

  $items['qtr/project/list'] = array(
    'type'            => MENU_NORMAL_ITEM,
    'title'           => 'Project List',
    'description'     => 'List of all the imported projects.',
    'page callback'   => 'qtrProject_projlist',
    'file'            => 'callback/projlist.inc',
    'access callback' => TRUE,
  );

  $items['qtr/project/%/%/%'] = array(
    'type'            => MENU_NORMAL_ITEM,
    'title'           => 'Project',
    'description'     => 'Review a random string from the project.',
    'page callback'   => 'qtrProject_random',
    'page arguments'  => array(2, 3, 4),
    'file'            => 'callback/random.inc',
    'access callback' => TRUE,
  );

  $items['qtr/project/%/%/%/dashboard'] = array(
    'type'            => MENU_LOCAL_TASK,
    'title'           => 'Dashboard',
    'description'     => 'Details of the project, statistics, latest activity, etc..',
    'page callback'   => 'qtrProject_dashboard',
    'page arguments'  => array(2, 3, 4),
    'file'            => 'callback/dashboard.inc',
    'access callback' => TRUE,
    'weight'          => 1,
  );

  $items['qtr/project/%/%/%/random'] = array(
    'type'            => MENU_DEFAULT_LOCAL_TASK,
    'title'           => 'Random',
    'weight'          => 2,
  );

  $items['qtr/project/%/%/%/list'] = array(
    'type'            => MENU_LOCAL_TASK,
    'title'           => 'List',
    'description'     => 'List strings and translations of the project.',
    'page callback'   => 'qtrProject_list',
    'page arguments'  => array(2, 3, 4),
    'file'            => 'callback/list.inc',
    'access callback' => TRUE,
    'weight'          => 3,
  );

  $items['qtr/project/%/%/%/search'] = array(
    'type'            => MENU_LOCAL_TASK,
    'title'           => 'Search',
    'description'     => 'Search strings and translations of the project.',
    'page callback'   => 'qtrProject_search',
    'page arguments'  => array(2, 3, 4),
    'file'            => 'callback/search.inc',
    'access callback' => TRUE,
    'weight'          => 4,
  );

  /*
  $items['qtr/project/%/%/%/edit'] = array(
    'type'            => MENU_LOCAL_TASK,
    'title'           => 'Edit',
    'description'     => 'Edit details of the project.',
    'page callback'   => 'qtrProject_edit',
    'page arguments'  => array(2, 3, 4),
    'file'            => 'callback/edit.inc',
    'access callback' => TRUE,
    'weight'          => 5,
  );
  */

  $items['qtr/project/%/%/%/admin'] = array(
    'type'            => MENU_LOCAL_TASK,
    'title'           => 'Admin',
    'description'     => 'Administrative tasks of the project.',
    'page callback'   => 'qtrProject_admin',
    'page arguments'  => array(2, 3, 4),
    'file'            => 'callback/admin.inc',
    'access callback' => TRUE,
    'weight'          => 6,
  );

  return $items;
}
