<?php
/**
 * @file
 * Module file for qtrTranslations.
 */

module_load_include('inc', 'qtrTranslations', 'blocks/blocks');

/**
 * Implements hook_init().
 */
function qtrTranslations_init() {
  // Include the stylesheets.
  $path = drupal_get_path('module', 'qtrTranslations');
  drupal_add_css($path . '/blocks/navigate.css.less');
  drupal_add_css($path . '/blocks/select.css.less');
  drupal_add_css($path . '/blocks/search.css.less');
}

/**
 * Implements hook_menu().
 */
function qtrTranslations_menu() {

  $items['qtr'] = array(
    'type'            => MENU_NORMAL_ITEM,
    'title'           => 'Translations',
    'description'     => 'Get a verse and its translations.',
    'page callback'   => 'qtrTranslations_get',
    'file'            => 'callback/get.inc',
    'access callback' => TRUE,
  );

  /*
  $items['qtr/get'] = array(
    'type'            => MENU_DEFAULT_LOCAL_TASK,
    'title'           => 'Get Translations',
    'weight'          => 1,
  );
  */

  $items['qtr/search'] = array(
    'type'            => MENU_LOCAL_TASK,
    'title'           => 'Search',
    'description'     => 'Search verses and translations using various filters.',
    'page callback'   => 'qtrTranslations_search',
    'file'            => 'callback/search.inc',
    'access callback' => TRUE,
    'weight'          => 2,
  );

  $items['qtr/export'] = array(
    'type'            => MENU_LOCAL_TASK,
    'title'           => 'Export',
    'description'     => 'Export translations to a file.',
    'page callback'   => 'qtrTranslations_export',
    'file'            => 'callback/export.inc',
    'access callback' => 'oauth2_user_is_authenticated',
    'weight'          => 3,
  );

  $items['qtr/import'] = array(
    'type'            => MENU_LOCAL_TASK,
    'title'           => 'Import',
    'description'     => 'Import translations from file.',
    'page callback'   => 'qtrTranslations_import',
    'file'            => 'callback/import.inc',
    'access callback' => 'oauth2_user_is_authenticated',
    'weight'          => 4,
  );

  return $items;
}
