<?php
/**
 * @file
 * Module file for qtrVocabulary.
 */

module_load_include('inc', 'qtrVocabulary', 'form_build');
module_load_include('inc', 'qtrVocabulary', 'form_submit');
module_load_include('inc', 'qtrVocabulary', 'blocks/blocks');

/**
 * Implements hook_init().
 */
function qtrVocabulary_init() {
  // Include the stylesheets.
  $path = drupal_get_path('module', 'qtrVocabulary');
  drupal_add_css($path . '/blocks/list.css.less');
}

/**
 * Implements hook_menu().
 */
function qtrVocabulary_menu() {
  $items['vocabulary'] = array(
    'title'           => 'Vocabulary',
    'description'     => 'Lookup vocabulary items.',
    'page callback'   => 'qtrVocabulary_page',
    'access callback' => TRUE,
  );

  $items['vocabulary/list'] = array(
    'type'            => MENU_NORMAL_ITEM,
    'title'           => 'Vocabulary List',
    'description'     => 'List of vocabularies.',
    'page callback'   => 'qtrVocabulary_list',
    'access callback' => TRUE,
  );

  $items['vocabularies'] = array(
    'type'            => MENU_NORMAL_ITEM,
    'title'           => 'Vocabulary List',
    'description'     => 'List of vocabularies.',
    'page callback'   => 'qtrVocabulary_list',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_menu_link_alter().
 */
function qtrVocabulary_menu_link_alter(&$item) {
  // Open vocabulary on a new tab.
  if ($item['link_path'] == 'vocabulary') {
    $item['options']['attributes']['target'] = '_blank';
  }
}

/**
 * Implements hook_theme().
 */
function qtrVocabulary_theme($existing, $type, $theme, $path) {
  return array(
    'qtrVocabulary_table' => array(
      'render element' => 'element',
    ),
  );
}

/**
 * Menu callback: vocabulary.
 */
function qtrVocabulary_page($vocabulary = NULL, $term = NULL) {
  if ($vocabulary == NULL) {
    $lng = qcl::get_translation_lng();
    $vocabulary = 'ICT_' . $lng;
    drupal_goto("vocabulary/$vocabulary");
  }

  // Set the page title.
  drupal_set_title(t('Vocabulary: !vocabulary',
      array('!vocabulary' => $vocabulary),
      array('context' => 'set the page title')));

  // Build and return the output.
  $output = drupal_get_form('qtrVocabulary_form', $vocabulary, $term);
  return $output;
}

/**
 * Menu callback: vocabulary/list
 */
function qtrVocabulary_list() {
  $output = [
    'vocabulary_list' => [
      '#prefix' => '<div class="row">',
      '#suffix' => '</div>',

      'list' => [
        '#prefix' => '<div class="col-sm-6">',
        qcl::get_block('qtrVocabulary', 'list'),
        '#suffix' => '</div>',
      ],

      'import' => [
        '#prefix' => '<div class="col-sm-6">',
        _qtrVocabulary_list_import(),
        qcl::get_block('qtrVocabulary', 'delete'),
        '#suffix' => '</div>',
      ],
    ],
  ];

  return $output;
}

/**
 * Import a vocabulary.
 */
function _qtrVocabulary_list_import() {
  $import = qcl::get_block('qtrVocabulary', 'import');
  $import['qtrVocabulary_import']['import']['#collapsible'] = TRUE;
  $import['qtrVocabulary_import']['import']['#collapsed'] = TRUE;
  return $import;
}
